-- MySQL Script generated by MySQL Workbench
-- mar 31 oct 2017 19:41:07 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- -----------------------------------------------------
-- Create user and DB
-- -----------------------------------------------------

CREATE USER IF NOT EXISTS 'fitnessuser'@'localhost'
  IDENTIFIED BY 'fitnesspass' ;
CREATE DATABASE IF NOT EXISTS `fitnessdb` DEFAULT CHARACTER SET utf8 ;
GRANT ALL PRIVILEGES ON `fitnessdb` . * TO 'fitnessuser'@'localhost' ;
use `fitnessdb` ;

-- -----------------------------------------------------
-- Table `fitnessdb`.`user`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` INT NULL,
  `dni` INT NULL,
  user_type ENUM('Administrador', 'Deportista', 'Entrenador') NOT NULL,
  athlete_type ENUM('TDU', 'PEF') NULL,
  `confirm_date` DATETIME NULL,
  `profile_image` VARCHAR(50) NULL,
  `description` VARCHAR(400) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`notification`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT,
  `date` DATETIME NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_user`)
    REFERENCES `fitnessdb`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`public_info`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`public_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` INT NULL,
  `email` VARCHAR(100) NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`exercise`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`exercise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `image` MEDIUMTEXT NULL,
  `video` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_user`)
    REFERENCES `fitnessdb`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`workout_table`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`workout_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_user`)
    REFERENCES `fitnessdb`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`activity`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `seats` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_user`)
    REFERENCES `fitnessdb`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`user_table`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`user_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_workout` INT,
  `id_user` INT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_user`)
    REFERENCES `fitnessdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  FOREIGN KEY (`id_workout`)
    REFERENCES `fitnessdb`.`workout_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`session`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT,
  `id_table` INT,
  `date` DATETIME NOT NULL,
  `duration` TIME NOT NULL,
  `comment` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_user`)
    REFERENCES `fitnessdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  FOREIGN KEY (`id_table`)
    REFERENCES `fitnessdb`.`user_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`resource`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`notification_user`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`notification_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT,
  `id_notification` INT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_user`)
    REFERENCES `fitnessdb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (`id_notification`)
    REFERENCES `fitnessdb`.`notification` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`exercise_table`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`exercise_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_exercise` INT,
  `id_workout` INT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_exercise`)
    REFERENCES `fitnessdb`.`exercise` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (`id_workout`)
    REFERENCES `fitnessdb`.`workout_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`activity_resource`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`activity_resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_activity` INT,
  `id_resource` INT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_activity`)
    REFERENCES `fitnessdb`.`activity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (`id_resource`)
    REFERENCES `fitnessdb`.`resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`activity_schedule`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`activity_schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_activity` INT,
  `date` DATE NOT NULL,
  `start_hour` TIME NOT NULL,
  `end_hour` TIME NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_activity`)
    REFERENCES `fitnessdb`.`activity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`user_activity`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`user_activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT,
  `id_activity` INT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_user`)
    REFERENCES `fitnessdb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (`id_activity`)
    REFERENCES `fitnessdb`.`activity_schedule` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitnessdb`.`assistance`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `fitnessdb`.`assistance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_userActivity` INT,
  `date` DATETIME NOT NULL,
  `assist` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_userActivity`)
    REFERENCES `fitnessdb`.`user_activity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

--------------------------------------------------------

/*
-- -----------------------------------------------------
-- Insert user
-- -----------------------------------------------------

INSERT INTO `fitnessdb`.`user` (`id`,`login`,`password`,`name`,`surname`,`email`,`phone`,`dni`,`confirm_date`) VALUES 
(0, '', '', '', '', '', '', '', '');

-- -----------------------------------------------------
-- Insert notification
-- -----------------------------------------------------

INSERT INTO `notification` (`id`,`id_user`,`date`,`title`,`content`) VALUES 
(0, '', '', '', '');

-- -----------------------------------------------------
-- Insert public_info
-- -----------------------------------------------------

INSERT INTO `public_info` (`id`,`phone`,`email`,`address`) VALUES
(0, '', '', '');

-- -----------------------------------------------------
-- Insert exercise
-- -----------------------------------------------------

INSERT INTO `exercise` (`id`,`id_user`,`name`,`description`,`type`,`image`,`video`) VALUES
(0, '', '', '', '', '', '');

-- -----------------------------------------------------
-- Insert workout_table
-- -----------------------------------------------------

INSERT INTO `workout_table` (`id`,`id_user`,`name`,`type`,`description`) VALUES
(0, '', '', '', '');


-- -----------------------------------------------------
-- Insert activity
-- -----------------------------------------------------

INSERT INTO `activity` (`id`,`id_user`,`name`,`description`,`place`,`type`,`seats`) VALUES
(0, '', '', '', '', '', '');

-- -----------------------------------------------------
-- Insert user_table
-- -----------------------------------------------------

INSERT INTO `user_table` (`id`,`id_workout`,`id_user`) VALUES
(0, '', '');

-- -----------------------------------------------------
-- Insert session
-- -----------------------------------------------------

INSERT INTO `session` (`id`,`id_user`,`id_table`,`date`,`duration`,`comment`) VALUES
(0, '', '', '', '', '');

-- -----------------------------------------------------
-- Insert resource
-- -----------------------------------------------------

INSERT INTO `resource` (`id`,`name`,`description`) VALUES
(0, '', '');

-- -----------------------------------------------------
-- Insert notification_user
-- -----------------------------------------------------

INSERT INTO `notification_user` (`id`,`id_user`,`id_notification`) VALUES
(0, '', '');

-- -----------------------------------------------------
-- Insert exercise_table
-- -----------------------------------------------------

INSERT INTO `exercise_table` (`id`,`id_exercise`,`id_workout`) VALUES
(0, '', '');

-- -----------------------------------------------------
-- Insert activity_resource
-- -----------------------------------------------------

INSERT INTO `activity_resource` (`id`,`id_activity`,`id_resource`) VALUES
(0, '', '');

-- -----------------------------------------------------
-- Insert activity_schedule
-- -----------------------------------------------------

INSERT INTO `activity_schedule` (`id`,`id_activity`,`date`,`start_hour`,`end_hour`) VALUES
(0, '', '', '', '');

-- -----------------------------------------------------
-- Insert user_activity
-- -----------------------------------------------------

INSERT INTO `user_activity` (`id`,`id_user`,`id_activity`) VALUES
(0, '', '');

-- -----------------------------------------------------
-- Insert assistance
-- -----------------------------------------------------

INSERT INTO `assistance` (`id`,`id_userActivity`,`date`,`assist`) VALUES
(0, '', '', '');

*/
